# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: src/communication/ps.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'src/communication/ps.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1asrc/communication/ps.proto\"$\n\x0fRegisterRequest\x12\x11\n\tworker_ip\x18\x01 \x01(\t\"9\n\rRegisterReply\x12\x11\n\tworker_id\x18\x01 \x01(\x05\x12\x15\n\rtotal_workers\x18\x02 \x01(\x05\"G\n\x0bPushRequest\x12\x11\n\tworker_id\x18\x01 \x01(\x05\x12\x11\n\tgradients\x18\x02 \x01(\x0c\x12\x12\n\nlocal_step\x18\x03 \x01(\x05\"\x1d\n\tPushReply\x12\x10\n\x08received\x18\x01 \x01(\x08\"!\n\x0c\x46\x65tchRequest\x12\x11\n\tworker_id\x18\x01 \x01(\x05\"5\n\nFetchReply\x12\x12\n\nparameters\x18\x01 \x01(\x0c\x12\x13\n\x0bglobal_step\x18\x02 \x01(\x05\"\'\n\x12JobFinishedRequest\x12\x11\n\tworker_id\x18\x01 \x01(\x05\"#\n\x10JobFinishedReply\x12\x0f\n\x07message\x18\x01 \x01(\t2\xd7\x01\n\x0fParameterServer\x12\x32\n\x0eRegisterWorker\x12\x10.RegisterRequest\x1a\x0e.RegisterReply\x12*\n\x0ePushGradrients\x12\x0c.PushRequest\x1a\n.PushReply\x12-\n\x0f\x46\x65tchParameters\x12\r.FetchRequest\x1a\x0b.FetchReply\x12\x35\n\x0bJobFinished\x12\x13.JobFinishedRequest\x1a\x11.JobFinishedReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.communication.ps_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERREQUEST']._serialized_start=30
  _globals['_REGISTERREQUEST']._serialized_end=66
  _globals['_REGISTERREPLY']._serialized_start=68
  _globals['_REGISTERREPLY']._serialized_end=125
  _globals['_PUSHREQUEST']._serialized_start=127
  _globals['_PUSHREQUEST']._serialized_end=198
  _globals['_PUSHREPLY']._serialized_start=200
  _globals['_PUSHREPLY']._serialized_end=229
  _globals['_FETCHREQUEST']._serialized_start=231
  _globals['_FETCHREQUEST']._serialized_end=264
  _globals['_FETCHREPLY']._serialized_start=266
  _globals['_FETCHREPLY']._serialized_end=319
  _globals['_JOBFINISHEDREQUEST']._serialized_start=321
  _globals['_JOBFINISHEDREQUEST']._serialized_end=360
  _globals['_JOBFINISHEDREPLY']._serialized_start=362
  _globals['_JOBFINISHEDREPLY']._serialized_end=397
  _globals['_PARAMETERSERVER']._serialized_start=400
  _globals['_PARAMETERSERVER']._serialized_end=615
# @@protoc_insertion_point(module_scope)
