# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from communication import ps_pb2 as communication_dot_ps__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in src/communication/ps_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ParameterServerStub(object):
    """ParameterServer (PS)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterWorker = channel.unary_unary(
                '/ParameterServer/RegisterWorker',
                request_serializer=communication_dot_ps__pb2.RegisterRequest.SerializeToString,
                response_deserializer=communication_dot_ps__pb2.RegisterReply.FromString,
                _registered_method=True)
        self.PushGradrients = channel.unary_unary(
                '/ParameterServer/PushGradrients',
                request_serializer=communication_dot_ps__pb2.PushRequest.SerializeToString,
                response_deserializer=communication_dot_ps__pb2.PushReply.FromString,
                _registered_method=True)
        self.FetchParameters = channel.unary_unary(
                '/ParameterServer/FetchParameters',
                request_serializer=communication_dot_ps__pb2.FetchRequest.SerializeToString,
                response_deserializer=communication_dot_ps__pb2.FetchReply.FromString,
                _registered_method=True)
        self.JobFinished = channel.unary_unary(
                '/ParameterServer/JobFinished',
                request_serializer=communication_dot_ps__pb2.JobFinishedRequest.SerializeToString,
                response_deserializer=communication_dot_ps__pb2.JobFinishedReply.FromString,
                _registered_method=True)


class ParameterServerServicer(object):
    """ParameterServer (PS)
    """

    def RegisterWorker(self, request, context):
        """Worker ac
        PS can return a unique worker_id and total worker numbers
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PushGradrients(self, request, context):
        """Worker push gradients,
        This is the key of E2, and will be blocked under sync.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchParameters(self, request, context):
        """Worker pull the most recent parameters
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def JobFinished(self, request, context):
        """worker reply all job finished
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ParameterServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterWorker,
                    request_deserializer=communication_dot_ps__pb2.RegisterRequest.FromString,
                    response_serializer=communication_dot_ps__pb2.RegisterReply.SerializeToString,
            ),
            'PushGradrients': grpc.unary_unary_rpc_method_handler(
                    servicer.PushGradrients,
                    request_deserializer=communication_dot_ps__pb2.PushRequest.FromString,
                    response_serializer=communication_dot_ps__pb2.PushReply.SerializeToString,
            ),
            'FetchParameters': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchParameters,
                    request_deserializer=communication_dot_ps__pb2.FetchRequest.FromString,
                    response_serializer=communication_dot_ps__pb2.FetchReply.SerializeToString,
            ),
            'JobFinished': grpc.unary_unary_rpc_method_handler(
                    servicer.JobFinished,
                    request_deserializer=communication_dot_ps__pb2.JobFinishedRequest.FromString,
                    response_serializer=communication_dot_ps__pb2.JobFinishedReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ParameterServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ParameterServer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ParameterServer(object):
    """ParameterServer (PS)
    """

    @staticmethod
    def RegisterWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ParameterServer/RegisterWorker',
            communication_dot_ps__pb2.RegisterRequest.SerializeToString,
            communication_dot_ps__pb2.RegisterReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PushGradrients(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ParameterServer/PushGradrients',
            communication_dot_ps__pb2.PushRequest.SerializeToString,
            communication_dot_ps__pb2.PushReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FetchParameters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ParameterServer/FetchParameters',
            communication_dot_ps__pb2.FetchRequest.SerializeToString,
            communication_dot_ps__pb2.FetchReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def JobFinished(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ParameterServer/JobFinished',
            communication_dot_ps__pb2.JobFinishedRequest.SerializeToString,
            communication_dot_ps__pb2.JobFinishedReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
